spring:
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    url: jdbc:h2:file:./data/graphql-api-server/graphql-api
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
